version: '3.8'
services:
  postfix:
    build: ../postfix
    image: custom-postfix:v1
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - '../maildata:/var/mail'
    hostname: mail.destevez.fpinfo.com.es
    environment:
      - DOMAIN=destevez.fpinfo.com.es
